services:
  database:
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "h9P9U27XBrcW"

volumes:
  db:
    driver: local